const bancoDeImagensHerois = [
    // --- ADULTOS (A) ---
    {"nome": "Arakni, 5L!P3D", "tipo": "ADULT", "arquivo": "heroes/slippy_a.jpg"},
    {"nome": "Arakni, Huntsman", "tipo": "ADULT", "arquivo": "heroes/arakni_hunt_a.jpg"},
    {"nome": "Arakni, Marionette", "tipo": "ADULT", "arquivo": "heroes/arakni_mario_a.jpg"},
    {"nome": "Aurora, Legacy of Tempest", "tipo": "ADULT", "arquivo": "heroes/aurora_l_a.jpg"},
    {"nome": "Aurora, Shooting Star", "tipo": "ADULT", "arquivo": "heroes/aurora_a.jpg"},
    {"nome": "Azalea, Ace in the Hole", "tipo": "ADULT", "arquivo": "heroes/azalea_a.jpg"},
    {"nome": "Betsy, Skin in the Game", "tipo": "ADULT", "arquivo": "heroes/betsy_a.jpg"},
    {"nome": "Bravo, Showstopper", "tipo": "ADULT", "arquivo": "heroes/bravo_a.jpg"},
    {"nome": "Bravo, Star of the Show", "tipo": "ADULT", "arquivo": "heroes/starvo.jpg"},
    {"nome": "Briar, Warden of Thorns", "tipo": "ADULT", "arquivo": "heroes/briar_a.jpg"},
    {"nome": "Chane, Bound by Shadow", "tipo": "ADULT", "arquivo": "heroes/chane_a.jpg"},
    {"nome": "Cindra, Dracai of Retribution", "tipo": "ADULT", "arquivo": "heroes/cindra_a.jpg"},
    {"nome": "Dash, Inventor Extraordinaire", "tipo": "ADULT", "arquivo": "heroes/dash_a.jpg"},
    {"nome": "Dash I/O", "tipo": "ADULT", "arquivo": "heroes/dash_io_a.jpg"},
    {"nome": "Dorinthea Ironsong", "tipo": "ADULT", "arquivo": "heroes/dorinthea_a.jpg"},
    {"nome": "Dromai, Ash Artist", "tipo": "ADULT", "arquivo": "heroes/dromai_a.jpg"},
    {"nome": "Enigma, Ledger of Ancestry", "tipo": "ADULT", "arquivo": "heroes/enigma_a.jpg"},
    {"nome": "Fai, Rising Rebellion", "tipo": "ADULT", "arquivo": "heroes/fai_a.jpg"},
    {"nome": "Fang, Dracai of Blades", "tipo": "ADULT", "arquivo": "heroes/fang_a.jpg"},
    {"nome": "Florian, Rotwood Harbinger", "tipo": "ADULT", "arquivo": "heroes/florian_a.jpg"},
    {"nome": "Gravy Bones, Shipwrecked Looter", "tipo": "ADULT", "arquivo": "heroes/gravybones_a.jpg"},
    {"nome": "Hala, Bladesaint of the Vow", "tipo": "ADULT", "arquivo": "heroes/hala_a.jpg"},
    {"nome": "Ira, Scarlet Revenger", "tipo": "ADULT", "arquivo": "heroes/ira_a.jpg"},
    {"nome": "Iyslander, Stormbind", "tipo": "ADULT", "arquivo": "heroes/iyslander_a.jpg"},
    {"nome": "Jarl Vetreiði", "tipo": "ADULT", "arquivo": "heroes/jarl_a.jpg"},
    {"nome": "Kano, Dracai of Aether", "tipo": "ADULT", "arquivo": "heroes/kano_a.jpg"},
    {"nome": "Kassai of the Golden Sand", "tipo": "ADULT", "arquivo": "heroes/kassai_gs_a.jpg"},
    {"nome": "Katsu, the Wanderer", "tipo": "ADULT", "arquivo": "heroes/katsu_a.jpg"},
    {"nome": "Kayo, Armed and Dangerous", "tipo": "ADULT", "arquivo": "heroes/kayo_a.jpg"},
    {"nome": "Kayo, Underhanded Cheat", "tipo": "ADULT", "arquivo": "heroes/rkayo_a.jpg"},
    {"nome": "Levia, Shadowborn Abomination", "tipo": "ADULT", "arquivo": "heroes/levia_a.jpg"},
    {"nome": "Lexi, Livewire", "tipo": "ADULT", "arquivo": "heroes/lexi_a.jpg"},
    {"nome": "Lyath Goldmane, Vile Savant", "tipo": "ADULT", "arquivo": "heroes/lyath_a.jpg"},
    {"nome": "Marlynn, Treasure Hunter", "tipo": "ADULT", "arquivo": "heroes/marlynn_a.jpg"},
    {"nome": "Maxx 'The Hype' Nitro", "tipo": "ADULT", "arquivo": "heroes/maxx_a.jpg"},
    {"nome": "Nuu, Alluring Desire", "tipo": "ADULT", "arquivo": "heroes/nuu_a.jpg"},
    {"nome": "Oldhim, Grandfather of Eternity", "tipo": "ADULT", "arquivo": "heroes/oldhim_a.jpg"},
    {"nome": "Olympia, Prized Fighter", "tipo": "ADULT", "arquivo": "heroes/olympia_a.jpg"},
    {"nome": "Oscilio, Constella Intelligence", "tipo": "ADULT", "arquivo": "heroes/oscilio_a.jpg"},
    {"nome": "Oscilio, Forked Continuum", "tipo": "ADULT", "arquivo": "heroes/broscilio_a.jpg"},
    {"nome": "Pleiades, Superstar", "tipo": "ADULT", "arquivo": "heroes/pleiades_a.jpg"},
    {"nome": "Prism, Awakener of Sol", "tipo": "ADULT", "arquivo": "heroes/prism_a.jpg"},
    {"nome": "Prism, Sculptor of Arc Light", "tipo": "ADULT", "arquivo": "heroes/prism_a.jpg"},
    {"nome": "Puffin, Hightail", "tipo": "ADULT", "arquivo": "heroes/puffin_a.jpg"},
    {"nome": "Rhinar, Reckless Rampage", "tipo": "ADULT", "arquivo": "heroes/rhinar_a.jpg"},
    {"nome": "Riptide, Lurker of the Deep", "tipo": "ADULT", "arquivo": "heroes/riptide_a.jpg"},
    {"nome": "Ser Boltyn, Breaker of Dawn", "tipo": "ADULT", "arquivo": "heroes/boltyn_a.jpg"},
    {"nome": "Teklovossen, Esteemed Magnate", "tipo": "ADULT", "arquivo": "heroes/teklovossen_a.jpg"},
    {"nome": "Tuffnut, Bumbling Hulkster", "tipo": "ADULT", "arquivo": "heroes/tuffnut_a.jpg"},
    {"nome": "Uzuri, Switchblade", "tipo": "ADULT", "arquivo": "heroes/uzuri_a.jpg"},
    {"nome": "Valda, Seismic Impact", "tipo": "ADULT", "arquivo": "heroes/valda_a.jpg"},
    {"nome": "Verdance, Thorn of the Rose", "tipo": "ADULT", "arquivo": "heroes/verdance_a.jpg"},
    {"nome": "Victor Goldmane, High and Mighty", "tipo": "ADULT", "arquivo": "heroes/victor_a.jpg"},
    {"nome": "Viserai, Rune Blood", "tipo": "ADULT", "arquivo": "heroes/viserai_a.jpg"},
    {"nome": "Vynnset, Iron Maiden", "tipo": "ADULT", "arquivo": "heroes/vynnset_a.jpg"},
    {"nome": "Zen, Tamer of Purpose", "tipo": "ADULT", "arquivo": "heroes/zen_a.jpg"},
    {"nome": "Zyggy Starlight", "tipo": "ADULT", "arquivo": "heroes/zyggy_a.jpg"},

    // --- JOVENS (Y) ---
    {"nome": "Arakni", "tipo": "YOUNG", "arquivo": "heroes/arakni_y.jpg"},
    {"nome": "Arakni, Solitary Confinement", "tipo": "YOUNG", "arquivo": "heroes/arakni_sc_y.jpg"},
    {"nome": "Arakni, Web of Deceit", "tipo": "YOUNG", "arquivo": "heroes/arakni_web_y.jpg"},
    {"nome": "Aurora", "tipo": "YOUNG", "arquivo": "heroes/aurora_y.jpg"},
    {"nome": "Aurora, Emissary of Lightning", "tipo": "YOUNG", "arquivo": "heroes/aurora_e_y.jpg"},
    {"nome": "Azalea", "tipo": "YOUNG", "arquivo": "heroes/azalea_y.jpg"},
    {"nome": "Baalghor, Omen of the End", "tipo": "YOUNG", "arquivo": "heroes/default.jpg"},
    {"nome": "Benji, the Piercing Wind", "tipo": "YOUNG", "arquivo": "heroes/benji_y.jpg"},
    {"nome": "Betsy", "tipo": "YOUNG", "arquivo": "heroes/betsy_y.jpg"},
    {"nome": "Blaze, Firemind", "tipo": "YOUNG", "arquivo": "heroes/blaze_y.jpg"},
    {"nome": "Bolfar, Bear Hands", "tipo": "YOUNG", "arquivo": "heroes/default.jpg"},
    {"nome": "Boltyn", "tipo": "YOUNG", "arquivo": "heroes/boltyn_y.jpg"},
    {"nome": "Bravo", "tipo": "YOUNG", "arquivo": "heroes/bravo_y.jpg"},
    {"nome": "Bravo, Flattering Showman", "tipo": "YOUNG", "arquivo": "heroes/bravo_fs_y.jpg"},
    {"nome": "Brevant, Civic Protector", "tipo": "YOUNG", "arquivo": "heroes/default.jpg"},
    {"nome": "Briar", "tipo": "YOUNG", "arquivo": "heroes/briar_y.jpg"},
    {"nome": "Brutus, Summa Rudis", "tipo": "YOUNG", "arquivo": "heroes/default.jpg"},
    {"nome": "Chane", "tipo": "YOUNG", "arquivo": "heroes/chane_y.jpg"},
    {"nome": "Cindra", "tipo": "YOUNG", "arquivo": "heroes/cindra_y.jpg"},
    {"nome": "Dash", "tipo": "YOUNG", "arquivo": "heroes/dash_y.jpg"},
    {"nome": "Dash, Database", "tipo": "YOUNG", "arquivo": "heroes/Dash_Database_y.jpg"},
    {"nome": "Data Doll MKII", "tipo": "YOUNG", "arquivo": "heroes/datadoll.jpg"},
    {"nome": "Dorinthea", "tipo": "YOUNG", "arquivo": "heroes/dorinthea_y.jpg"},
    {"nome": "Dorinthea Quicksilver Prodigy", "tipo": "YOUNG", "arquivo": "heroes/dorinthea_y.jpg"},
    {"nome": "Dromai", "tipo": "YOUNG", "arquivo": "heroes/dromai_y.jpg"},
    {"nome": "Emperor, Dracai of Aesir", "tipo": "YOUNG", "arquivo": "heroes/emperor.jpg"},
    {"nome": "Enigma", "tipo": "YOUNG", "arquivo": "heroes/enigma_y.jpg"},
    {"nome": "Enigma, New Moon", "tipo": "YOUNG", "arquivo": "heroes/default.jpg"},
    {"nome": "Fai", "tipo": "YOUNG", "arquivo": "heroes/fai_y.jpg"},
    {"nome": "Fang", "tipo": "YOUNG", "arquivo": "heroes/fang_y.jpg"},
    {"nome": "Fightmaster Kox", "tipo": "YOUNG", "arquivo": "heroes/default.jpg"},
    {"nome": "Florian", "tipo": "YOUNG", "arquivo": "heroes/florian_y.jpg"},
    {"nome": "Frankie, Make Ends Meat", "tipo": "YOUNG", "arquivo": "heroes/default.jpg"},
    {"nome": "Genis Wotchuneed", "tipo": "YOUNG", "arquivo": "heroes/genis.jpg"},
    {"nome": "Gravy Bones", "tipo": "YOUNG", "arquivo": "heroes/gravybones_y.jpg"},
    {"nome": "Groundbreaker Crix", "tipo": "YOUNG", "arquivo": "heroes/default.jpg"},
    {"nome": "Hala", "tipo": "YOUNG", "arquivo": "heroes/hala_y.jpg"},
    {"nome": "Ira, Crimson Haze", "tipo": "YOUNG", "arquivo": "heroes/ira_y.jpg"},
    {"nome": "Iyslander", "tipo": "YOUNG", "arquivo": "heroes/iyslander_y.jpg"},
    {"nome": "Kano", "tipo": "YOUNG", "arquivo": "heroes/kano_y.jpg"},
    {"nome": "Kassai", "tipo": "YOUNG", "arquivo": "heroes/kassai_y.jpg"},
    {"nome": "Kassai, Cintari Sellsword", "tipo": "YOUNG", "arquivo": "heroes/Kaasai_Cs_Y.jpg"},
    {"nome": "Katsu", "tipo": "YOUNG", "arquivo": "heroes/katsu_y.jpg"},
    {"nome": "Kavdaen, Trader of Skins", "tipo": "YOUNG", "arquivo": "heroes/kavdaen.jpg"},
    {"nome": "Kayo", "tipo": "YOUNG", "arquivo": "heroes/kayo_y.jpg"},
    {"nome": "Kayo, Berserker Runt", "tipo": "YOUNG", "arquivo": "heroes/kayo_dice_y.jpg"},
    {"nome": "Kayo, Strong-arm", "tipo": "YOUNG", "arquivo": "heroes/kayo_sa_y.jpg"},
    {"nome": "Levia", "tipo": "YOUNG", "arquivo": "heroes/levia_y.jpg"},
    {"nome": "Lexi", "tipo": "YOUNG", "arquivo": "heroes/lexi_y.jpg"},
    {"nome": "Lyath Goldmane", "tipo": "YOUNG", "arquivo": "heroes/lyath_y.jpg"},
    {"nome": "Marlynn", "tipo": "YOUNG", "arquivo": "heroes/marlynn_y.jpg"},
    {"nome": "Maxx Nitro", "tipo": "YOUNG", "arquivo": "heroes/maxx_y.jpg"},
    {"nome": "Melody, Sing-along", "tipo": "YOUNG", "arquivo": "heroes/default.jpg"},
    {"nome": "Nuu", "tipo": "YOUNG", "arquivo": "heroes/nuu_y.jpg"},
    {"nome": "Oldhim", "tipo": "YOUNG", "arquivo": "heroes/oldhim_y.jpg"},
    {"nome": "Olympia", "tipo": "YOUNG", "arquivo": "heroes/olympia_y.jpg"},
    {"nome": "Oscilio", "tipo": "YOUNG", "arquivo": "heroes/oscilio_y.jpg"},
    {"nome": "Oscilio, Scion of the Third Age", "tipo": "YOUNG", "arquivo": "heroes/oscilio_s_y.jpg"},
    {"nome": "Pleiades", "tipo": "YOUNG", "arquivo": "heroes/pleiades_y.jpg"},
    {"nome": "Prism", "tipo": "YOUNG", "arquivo": "heroes/prism_y.jpg"},
    {"nome": "Prism, Advent of Thrones", "tipo": "YOUNG", "arquivo": "heroes/prism_at_y.jpg"},
    {"nome": "Professor Teklovossen", "tipo": "YOUNG", "arquivo": "heroes/teklovossen_y.jpg"},
    {"nome": "Puffin", "tipo": "YOUNG", "arquivo": "heroes/puffin_y.jpg"},
    {"nome": "Reya, the Unyielding", "tipo": "YOUNG", "arquivo": "heroes/default.jpg"},
    {"nome": "Rhinar", "tipo": "YOUNG", "arquivo": "heroes/rhinar_y.jpg"},
    {"nome": "Riptide", "tipo": "YOUNG", "arquivo": "heroes/riptide_y.jpg"},
    {"nome": "Scurv, Stowaway", "tipo": "YOUNG", "arquivo": "heroes/default.jpg"},
    {"nome": "Shiyana, Diamond Gemini", "tipo": "YOUNG", "arquivo": "heroes/shiyana.jpg"},
    {"nome": "Squizzy & Floof", "tipo": "YOUNG", "arquivo": "heroes/default.jpg"},
    {"nome": "Taipanis, Dracai of Judgement", "tipo": "YOUNG", "arquivo": "heroes/default.jpg"},
    {"nome": "Taylor", "tipo": "YOUNG", "arquivo": "heroes/default.jpg"},
    {"nome": "Teklovossen", "tipo": "YOUNG", "arquivo": "heroes/teklovossen_y.jpg"},
    {"nome": "Terra", "tipo": "YOUNG", "arquivo": "heroes/default.jpg"},
    {"nome": "The Librarian, Magister of History", "tipo": "YOUNG", "arquivo": "heroes/default.jpg"},
    {"nome": "Theryon, Magister of Justice", "tipo": "YOUNG", "arquivo": "heroes/default.jpg"},
    {"nome": "Tuffnut", "tipo": "YOUNG", "arquivo": "heroes/tuffnut_y.jpg"},
    {"nome": "Uzuri", "tipo": "YOUNG", "arquivo": "heroes/uzuri_y.jpg"},
    {"nome": "Valda Brightaxe", "tipo": "YOUNG", "arquivo": "heroes/valda_y.jpg"},
    {"nome": "Verdance", "tipo": "YOUNG", "arquivo": "heroes/verdance_y.jpg"},
    {"nome": "Victor Goldmane", "tipo": "YOUNG", "arquivo": "heroes/victor_y.jpg"},
    {"nome": "Victor Goldmane, Match Fixer", "tipo": "ADULT", "arquivo": "heroes/victor_a.jpg"},
    {"nome": "Viserai", "tipo": "YOUNG", "arquivo": "heroes/viserai_y.jpg"},
    {"nome": "Vynnset", "tipo": "YOUNG", "arquivo": "heroes/vynnset_y.jpg"},
    {"nome": "Yoji, Royal Protector", "tipo": "YOUNG", "arquivo": "heroes/yoji.jpg"},
    {"nome": "Yorick, Weaver of Tales", "tipo": "YOUNG", "arquivo": "heroes/default.jpg"},
    {"nome": "Zen", "tipo": "YOUNG", "arquivo": "heroes/zen_y.jpg"},
    {"nome": "Zyggy", "tipo": "YOUNG", "arquivo": "heroes/zyggy_y.jpg"}
];